instagram/instagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from instagram import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from webapp.views import PostsListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, \
    FollowersView, LikePostView

app_name = "webapp"

urlpatterns = [
    path('', PostsListView.as_view(), name="posts_list"),
    path('posts/add/', PostCreateView.as_view(), name="post_add"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_view"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/like/', LikePostView.as_view(), name="post_like"),
    path('user/<int:pk>/follower/', FollowersView.as_view(), name="follower")
]

instagram/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class CreateUpdateAbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Post(CreateUpdateAbstractModel):
    image = models.ImageField(upload_to="posts", verbose_name='Картинка')
    content = models.TextField(max_length=2000, verbose_name="Контент")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="posts", verbose_name="Автор")
    like_users = models.ManyToManyField(get_user_model(), related_name='like_posts', verbose_name="Лайки")

    def __str__(self):
        return f"{self.pk} {self.author}"

    def get_absolute_url(self):
        return reverse("webapp:post_view", kwargs={"pk": self.pk})

    class Meta:
        db_table = "posts"
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

instagram/webapp/forms.py
from django import forms

from webapp.models import Post


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content", "image"]

instagram/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PostForm
from webapp.models import Post


class PostsListView(ListView):
    model = Post
    template_name = "posts/posts_list.html"
    context_object_name = "posts"
    paginate_by = 3
    ordering = ("-created_at",)

    def get_queryset(self):
        posts = super().get_queryset()
        if self.request.user.is_authenticated:
            posts = super().get_queryset().filter(author__in=self.request.user.following.all())
        return posts


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = "posts/post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_update.html"

    def has_permission(self):
        return self.request.user == self.get_object().author


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"

    def has_permission(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = "posts/post_view.html"


class FollowersView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        if user == request.user:
            return HttpResponseBadRequest()
        if request.userkill in user.followers.all():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
        return redirect("accounts:profile", pk=pk)


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        if request.user in post.like_users.all():
            post.like_users.remove(request.user)
        else:
            post.like_users.add(request.user)
        return HttpResponseRedirect(self.request.GET.get("next"))

instagram/webapp/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %}Создание{% endblock %}
<h1>Создание</h1>

{% block content %}
    {% include "partial/form.html" with button_text="Создать" %}
{% endblock %}

instagram/webapp/templates/posts/post_delete.html
{% extends "base.html" %}

{% block content %}
    <h3>Вы уверены что хотите удалить продукт этот пост?</h3>
    <form action="" method="post">
        {% csrf_token %}
        <button>Да</button>
    </form>
    <a href="{% url "webapp:post_view" post.pk %} ">Нет</a>
{% endblock %}

instagram/webapp/templates/posts/post_update.html
{% extends "base.html" %}

{% block title %}Редактирование{% endblock %}
<h1>Редактирование</h1>

{% block content %}
    {% include "partial/form.html" with button_text="Изменить" %}
{% endblock %}

instagram/webapp/templates/posts/post_view.html
{% extends "base.html" %}

{% block link %}
    {% if request.user == post.author %}
        <li class="nav-item">
            <a href="{% url "webapp:post_update" post.pk %}" class="nav-link">Редактирование</a>
        </li>
        <li class="nav-item">
            <a href="{% url "webapp:post_delete" post.pk %}" class="nav-link">Удаление</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    {% include "partial/post_view_partial.html" %}

{% endblock %}

instagram/webapp/templates/posts/posts_list.html
{% extends "base.html" %}

{% block link %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:post_add" %}">Создание поста</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <br>
    <div class="row">
        {% for post in posts %}
            {% include "partial/post_view_partial.html" %}
        {% empty %}
            <h2>Нет постов</h2>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}