instagram/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserPasswordChangeView, UserChangeView, UsersListView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('<int:pk>/profile/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UsersListView.as_view(), name="users_list"),
]

instagram/instagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from instagram import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from webapp.views import PostsListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, \
    FollowersView, LikePostView

app_name = "webapp"

urlpatterns = [
    path('', PostsListView.as_view(), name="posts_list"),
    path('posts/add/', PostCreateView.as_view(), name="post_add"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_view"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/like/', LikePostView.as_view(), name="post_like"),
    path('user/<int:pk>/follower/', FollowersView.as_view(), name="follower")
]

instagram/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager, Group, Permission
from django.db import models


class CustomUserManager(UserManager):
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]

    def males(self):
        return self.filter(gender=self.GENDER_MALE)

    def females(self):
        return self.filter(gender=self.GENDER_FEMALE)


class Userkill(AbstractUser):
    avatar = models.ImageField(upload_to="avatars", verbose_name='Аватар')
    description = models.TextField(max_length=2000, verbose_name="Информация", blank=True, null=True)
    phone = models.CharField(max_length=30, verbose_name="Номер телефона", blank=True, null=True)
    gender = models.IntegerField(choices=CustomUserManager.GENDER_CHOICES)
    followers = models.ManyToManyField('self', related_name='following', verbose_name="Подписки", symmetrical=False)

    objects = CustomUserManager()
    groups = models.ManyToManyField(
        Group,
        blank=True,
        related_name='userkill_groups'
    )
    user_permissions = models.ManyToManyField(
        Permission,
        blank=True,
        related_name='userkill_user_permissions'
    )

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'userkills'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователь'

instagram/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class MyUserCreationForm(UserCreationForm):
    avatar = forms.ImageField()

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username',
                  'password1',
                  'password2',
                  'first_name',
                  'description',
                  'gender',
                  'avatar']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

instagram/accounts/views.py
from urllib.parse import urlencode

from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from accounts.forms import MyUserCreationForm, UserChangeForm
from webapp.forms import SearchForm


class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class ProfileView(DetailView):
    model = get_user_model()
    template_name = "profile.html"
    context_object_name = "user_obj"
    # paginate_related_by = 2


class UserChangeView(PermissionRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def has_permission(self):
        return self.request.user == self.get_object()

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})


class UsersListView(ListView):
    model = get_user_model()
    template_name = "users_list.html"
    context_object_name = "users"

    def dispatch(self, request, *args, **kwargs):

        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["form"] = self.form
        if self.search_value:
            context["query"] = urlencode({'search': self.search_value})
            context["search_value"] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(username__icontains=self.search_value) |
                                       Q(first_name__icontains=self.search_value) |
                                       Q(email__icontains=self.search_value))
        return queryset

instagram/accounts/templates/login.html
{% extends "base.html" %}
{% block content %}
    <h1>Вход</h1>
    <form action="" method="post" class="text-center w-50 ms-auto me-auto">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input class="form-control" type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input class="form-control" type="password" name="password" id="password">
        </div>
        <button class="btn btn-outline-dark mt-3" type="submit">Войти</button>
    </form>
{% endblock %}

instagram/accounts/templates/profile.html
{% extends "base.html" %}
{% block link %}
    {% if request.user.is_authenticated and user_obj == request.user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:password_change' %}">Смена пароля</a>
        </li>
    {% endif %}
{% endblock %}


{% block content %}
    <div class="profile-header">
        <img class="profile-avatar img-fluid" src="{{ user_obj.avatar.url }}" alt="User Avatar">
        <div class="profile-username">{{ user_obj.username }}</div>
        <div class="profile-bio">{{ user_obj.description }}</div>
        <div class="profile-stats">
            <div class="profile-stat-item">
                <span class="profile-stat-value">{{ user_obj.posts.count }}</span> posts
            </div>
            <div class="profile-stat-item">
                <span class="profile-stat-value">{{ user_obj.followers.count }}</span> followers
            </div>
            <div class="profile-stat-item">
                <span class="profile-stat-value">{{ user_obj.following.count }}</span> following
            </div>
        </div>
        {% if request.user.is_authenticated and request.user != user_obj %}
            <a href="{% url "webapp:follower" user_obj.pk %}">
                {% if request.user in user_obj.followers.all %}
                    Отписаться
                {% else %}
                    Подписаться
                {% endif %}
            </a>
        {% endif %}
    </div>
    <div class="profile-posts mt-5">
        <div class="row">
            {% for post in user_obj.posts.all %}
                <div class="col-md-4 mb-4">
                    <a href="{% url "webapp:post_view" post.pk %}">
                        <img class="post-thumbnail img-fluid" src="{{ post.image.url }}"
                             alt="{{ post.image.filename }}">
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

instagram/accounts/templates/user_change.html
{% extends "base.html" %}
{% block content %}
    <h1>Поменять личные данные</h1>

        {% include 'partial/form.html' with button_text='Редактировать' %}


{% endblock %}

instagram/accounts/templates/user_create.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}
<h1>Регистрация</h1>

{% block content %}
    {% include "partial/form.html" with button_text="Зарегестрироваться" %}
{% endblock %}

instagram/accounts/templates/user_password_change.html
{% extends "base.html" %}
{% block content %}
    <h1>Поменять пароль</h1>
    {% include 'partial/form.html' with button_text="Изменить" %}


{% endblock %}

instagram/accounts/templates/users_list.html
{% extends "base.html" %}
{% block content %}

    {% include "partial/form.html" with button_text='Поиск' method='get' %}
    <div class="row">
        {% for user in users %}
            <a href="{% url 'accounts:profile' userkill.pk %}">
                <div class="col-md-4">
                    <div class="user-card">
                        <img class="user-avatar img-fluid" src="{{ userkill.avatar.url }}" alt="{{ userkill.avatar.filename }}">
                        <div class="user-username">{{ userkill.username }}</div>
                        <div class="user-bio">{{ userkill.description }}</div>
                    </div>
                </div>
            </a>

        {% endfor %}
    </div>
{% endblock %}