instagram/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserPasswordChangeView, UserChangeView, UsersListView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('<int:pk>/profile/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UsersListView.as_view(), name="users_list"),
]

instagram/instagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from instagram import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from webapp.views import PostsListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, \
    FollowersView, LikePostView

app_name = "webapp"

urlpatterns = [
    path('', PostsListView.as_view(), name="posts_list"),
    path('posts/add/', PostCreateView.as_view(), name="post_add"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_view"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/like/', LikePostView.as_view(), name="post_like"),
    path('user/<int:pk>/follower/', FollowersView.as_view(), name="follower")
]

instagram/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class CreateUpdateAbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Post(CreateUpdateAbstractModel):
    image = models.ImageField(upload_to="posts", verbose_name='Картинка')
    content = models.TextField(max_length=2000, verbose_name="Контент")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="posts", verbose_name="Автор")
    like_users = models.ManyToManyField(get_user_model(), related_name='like_posts', verbose_name="Лайки")

    def __str__(self):
        return f"{self.pk} {self.author}"

    def get_absolute_url(self):
        return reverse("webapp:post_view", kwargs={"pk": self.pk})

    class Meta:
        db_table = "posts"
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

instagram/webapp/forms.py
from django import forms

from webapp.models import Post


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content", "image"]

instagram/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PostForm
from webapp.models import Post


class PostsListView(ListView):
    model = Post
    template_name = "posts/posts_list.html"
    context_object_name = "posts"
    paginate_by = 3
    ordering = ("-created_at",)

    def get_queryset(self):
        posts = super().get_queryset()
        if self.request.user.is_authenticated:
            posts = super().get_queryset().filter(author__in=self.request.user.following.all())
        return posts


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = "posts/post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_update.html"

    def has_permission(self):
        return self.request.user == self.get_object().author


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"

    def has_permission(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = "posts/post_view.html"


class FollowersView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        if user == request.user:
            return HttpResponseBadRequest()
        if request.userkill in user.followers.all():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
        return redirect("accounts:profile", pk=pk)


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        if request.user in post.like_users.all():
            post.like_users.remove(request.user)
        else:
            post.like_users.add(request.user)
        return HttpResponseRedirect(self.request.GET.get("next"))

instagram/webapp/templates/partial/form.html
<form action="{{ action_url }}" enctype="multipart/form-data" method="{{ method|default:'post' }}">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}


    {% for field in form %}
        <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
        {% for error in field.errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
        <p>{{ field }}</p>
    {% endfor %}

    <br/>
    <input type="submit" value="{{ button_text }}"/>
</form>

instagram/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <input type="hidden" name="search" value="{{ search_value }}">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

instagram/webapp/templates/partial/post_view_partial.html
<div class="post bg-white border rounded">
    <div class="post-header py-3 px-4 d-flex align-items-center">
        <img class="post-avatar rounded-circle me-3" src="{{ post.author.avatar.url }}" alt="User Avatar">
        <span class="post-username font-weight-bold"><a href="{% url 'accounts:profile' post.author.pk %}">
                        {{ post.author.username }}</a>
                    </span>
    </div>
    <img class="post-image img-fluid" src="{{ post.image.url }}" alt="Post Image">
    <div class="post-actions py-2 px-4">
        {% if request.user.is_authenticated %}
            <a href="{% url 'webapp:post_like' post.pk %}?next={{ request.path }}">
                {% if request.user not in post.like_users.all %}
                    <span class="post-like-btn me-2"><i class="bi bi-heart"></i></span>
                {% else %}
                    <span class="post-like-btn me-2"><i class="bi bi-heart-fill"></i></span>
                {% endif %}
            </a>
        {% endif %}
        <span class="post-likes font-weight-bold">{{ post.like_users.count }}</span>

        <span class="post-comment-btn me-2"><i class="bi bi-chat-dots-fill"></i></span>
    </div>
    <div class="post-description px-4 py-3">
        <p>{{ post.content }}</p>
    </div>
    <div class="post-timestamp px-4 py-2 text-muted">{{ post.created_at }}</div>

</div>

instagram/webapp/templates/partial/search_form.html
<form class="text-center" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Поиск">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>