instagram/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserPasswordChangeView, UserChangeView, UsersListView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('<int:pk>/profile/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UsersListView.as_view(), name="users_list"),
]

instagram/instagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from instagram import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from webapp.views import PostsListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, \
    FollowersView, LikePostView

app_name = "webapp"

urlpatterns = [
    path('', PostsListView.as_view(), name="posts_list"),
    path('posts/add/', PostCreateView.as_view(), name="post_add"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_view"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/like/', LikePostView.as_view(), name="post_like"),
    path('user/<int:pk>/follower/', FollowersView.as_view(), name="follower")
]

instagram/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class CreateUpdateAbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Post(CreateUpdateAbstractModel):
    image = models.ImageField(upload_to="posts", verbose_name='Картинка')
    content = models.TextField(max_length=2000, verbose_name="Контент")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="posts", verbose_name="Автор")
    like_users = models.ManyToManyField(get_user_model(), related_name='like_posts', verbose_name="Лайки")

    def __str__(self):
        return f"{self.pk} {self.author}"

    def get_absolute_url(self):
        return reverse("webapp:post_view", kwargs={"pk": self.pk})

    class Meta:
        db_table = "posts"
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

instagram/webapp/forms.py
from django import forms

from webapp.models import Post


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content", "image"]

instagram/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PostForm
from webapp.models import Post


class PostsListView(ListView):
    model = Post
    template_name = "posts/posts_list.html"
    context_object_name = "posts"
    paginate_by = 3
    ordering = ("-created_at",)

    def get_queryset(self):
        posts = super().get_queryset()
        if self.request.user.is_authenticated:
            posts = super().get_queryset().filter(author__in=self.request.user.following.all())
        return posts


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = "posts/post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_update.html"

    def has_permission(self):
        return self.request.user == self.get_object().author


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"

    def has_permission(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = "posts/post_view.html"


class FollowersView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        if user == request.user:
            return HttpResponseBadRequest()
        if request.userkill in user.followers.all():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
        return redirect("accounts:profile", pk=pk)


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        if request.user in post.like_users.all():
            post.like_users.remove(request.user)
        else:
            post.like_users.add(request.user)
        return HttpResponseRedirect(self.request.GET.get("next"))

instagram/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="{% url "webapp:posts_list" %}">Инстаграмм</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                {% block link %}
                {% endblock %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url "accounts:users_list" %}">Пользователи</a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:logout" %}">Выход</a>
                    </li>
                    <li class="nav-item">
                        <p>Здравствуйте <a
                                href="{% url "accounts:profile" request.user.pk %}">{{ request.user.username }} </a></p>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:register" %}?next={{ request.path }}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.path }}">Вход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}
        <h1>test</h1>
    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>